version: '3.8'

services:
  # Blockchain Node
  blockchain:
    build:
      context: .
      dockerfile: docker/blockchain.Dockerfile
    container_name: magi-blockchain
    ports:
      - "8545:8545"  # RPC endpoint
      - "30303:30303" # P2P port
    volumes:
      - blockchain_data:/blockchain
      - ./config/genesis.json:/config/genesis.json
    environment:
      - NETWORK_ID=403
      - CONSENSUS=poa
      - BLOCK_TIME=1000
      - INSTANCE_ID=NAS-001
    networks:
      - magi-network
    restart: unless-stopped

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5-community
    container_name: magi-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/magichain2025
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    networks:
      - magi-network
    restart: unless-stopped

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: magi-qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=magi-vector-key-2025
    networks:
      - magi-network
    restart: unless-stopped

  # MCP Memory Blockchain Server
  mcp-memory:
    build:
      context: .
      dockerfile: docker/mcp.Dockerfile
    container_name: magi-memory-mcp
    ports:
      - "5010:5010"  # MCP server port
    volumes:
      - ./mcp_memory_blockchain:/app/mcp_memory_blockchain
      - ./config:/app/config
    environment:
      - BLOCKCHAIN_URL=http://blockchain:8545
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=magichain2025
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=magi-vector-key-2025
      - TIME_PRECISION_URL=http://host.docker.internal:5009  # Assuming time MCP on host
      - INSTANCE_ID=NAS-001
      - LOG_LEVEL=INFO
    depends_on:
      - blockchain
      - neo4j
      - qdrant
    networks:
      - magi-network
    restart: unless-stopped

  # Migration Helper Service
  migration:
    build:
      context: .
      dockerfile: docker/migration.Dockerfile
    container_name: magi-migration
    volumes:
      - ./scripts:/app/scripts
      - ./migration_data:/app/data
    environment:
      - OLD_MEMORY_URL=http://host.docker.internal:5000  # Current memory MCP
      - NEW_MEMORY_URL=http://mcp-memory:5010
      - BLOCKCHAIN_URL=http://blockchain:8545
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=magichain2025
    networks:
      - magi-network
    profiles:
      - migration  # Only run when explicitly requested

networks:
  magi-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  blockchain_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  qdrant_data:
    driver: local